### ISSUE TITLE
Shape of Tensor of Vectors/Matrices

### ISSUE THREAD

**Issue by vkurenkov** [taichi-dev/taichi#1069]
As of now, the .shape() function works only for tensors of scalars. But it can be useful (e.g. for debugging purposes) to know the shape of the tensors of vectors/matrices.

```
# Tensor of scalars
x = ti.var(shape=(3, 2), dt=ti.f32)
# Tensor of vectors
y = ti.Vector(2, shape=(3), dt=ti.f32)

@ti.kernel
def test_tensor_of_scalars():
    # Works fine
    print(x.shape())

@ti.kernel
def test_tensor_of_vectors():
    # AttributeError: 'Matrix' object has no attribute 'shape'
    print(y.shape())
```

The same logic could be applied to ```.dim()``` as well. One potential drawback I can see from the user side is the possibility to misinterpret the indexing (```x[2][1]``` vs ```x[2, 1]```) as a consequence.

**Comment by archibate** [comment]
> As of now, the .shape() function works only for tensors of scalars. But it can be useful (e.g. for debugging purposes) to know the shape of the tensors of vectors/matrices.

Thank for purposing! This seems to be a missing feature of `Matrix`.

> The same logic could be applied to .dim() as well. One potential drawback I can see from the user side is the possibility to misinterpret the indexing (x[2][1] vs x[2, 1]) as a consequence.

Yes, so the problem is should `y.shape()` return `(2)` or `(2, 3)` here? I think we can simply return `(2)`, since user could access the vector dimension by `y.n`, which is `3`. For example:
```py
z = ti.Matrix(2, 3, shape=(6, 7), dt=ti.f32)
print(z.n)         # 2
print(z.m)         # 3
print(z.shape())   # (6, 7)   not implemented yet
```

Note that `y.entries[0]` is the tensor-of-scalar of the first component of `y`. So we can implement `y.shape()` by `y.entries[0].shape()`, since `entries[0]` and `entries[1]` are same in shape/dim.
