### ISSUE TITLE
Revamp dependencies and build system

### ISSUE THREAD

**Issue by kigawas** [taichi-dev/taichi#1096]
- Separate dependecies and dev-dependencies (like pytest), pyproject.toml could be an option

- Make it easier to build and deploy

Several links which may be helpful
- https://github.com/dephell/dephell
- https://github.com/python-poetry/poetry
- https://github.com/apache/incubator-mxnet/blob/master/python/setup.py
- https://github.com/scikit-learn/scikit-learn/blob/master/setup.py

**Comment by rexwangcc** [comment]
Thanks for the suggestion! Unpacking the links provided above, I think this issue proposed discussions around 2 points:

1. Separate dev/test-deps from the main deps
2. Switch to use other dependency managers such as `poetry`

While I strongly agree with `1.` and I believe it's something feasible to do in very short term, `2.` requires more changes to the whole packaging, CI and releasing process, since `poetry` specifically does not yet provide a native support for generating `setup.py` which might still be useful for some of the CI/dev tools at the moment.

**Comment by liaopeiyuan** [comment]
If I'm getting it right, is it true that currently we only support MacOS build on Travis CI? Could be a bit more helpful to add Linux/Windows builds for more sanity checks, and maybe older version builds to address confusions like #1099.

Additionally, are we considering something related to code coverage?

**Comment by rexwangcc** [comment]
We do have Linux build and [Windows build](https://ci.appveyor.com/project/yuanming-hu/taichi/branch/master), but we don't have any tests cases for the CLI which is a tech debt.

#1085 is trying to refactor the CLI and add test cases to avoid something like #1099 to happen in the future. But until it's out, I expect we'd receive more protability issues as more users are trying to ramp up with Taichi from different platforms 😅 .

**Comment by archibate** [comment]
FYI currently we use GitHub Actions as Linux build (#1023), AppVeyor as Windows build. We're considering to merge Windows & Mac OS X build into GitHub Actions, and purchase a self-hosted GitHub Actions runner at some point.

> Additionally, are we considering something related to code coverage?

Yes, see #677, codecov.
