### ISSUE TITLE
Something wrong with Cornell box example

### ISSUE THREAD

**Issue by leo-luo-lzy** [taichi-dev/taichi#1128]
- os: macOS Catalina 10.15.5
- Python version: 3.7.0
- taichi version: 0.6.7

It seems that there is something wrong with the example 'Cornell box' .
Thanks for your help in advance.
![Screenshot 2020-06-03 at 4 38 35 PM](https://user-images.githubusercontent.com/66378748/83664341-74509080-a5fc-11ea-863a-b7d5e3436dc6.png)
![Screenshot 2020-06-03 at 4 44 15 PM](https://user-images.githubusercontent.com/66378748/83664381-7f0b2580-a5fc-11ea-9198-7e89b1891555.png)

**Comment by rexwangcc** [comment]
The error itself seems like a numpy warning indicating `img / img.mean() * 0.24` got a negative number therefore all `var` become `nan`. But I failed to reproduce it with:
```
[Taichi] mode=release
[Taichi] version 0.6.7, supported archs: [cpu, metal], commit ca4d9dda, python 3.7.7
```

**Comment by TH3CHARLie** [comment]
Would you mind sharing your numpy info via `pip show numpy`? I can not reproduce this on my mac either.

**Comment by leo-luo-lzy** [comment]
> pip show numpy

![Screenshot 2020-06-04 at 1 26 21 AM](https://user-images.githubusercontent.com/66378748/83668392-71589e80-a602-11ea-9e18-9b7d172ac768.png)
Here it is. Thank you!

**Comment by k-ye** [comment]
Hi,

Thank you for reporting this!

This is an issue due to the graphics card. My MBP has two cards:

1. AMD Radeon Pro 5500M
2. Intel(R) UHD Graphics 630

I can repro this on 2, but not 1. My wild guess would be that this was due to some floating point arithmetics differences. Maybe some denominators were close to zero and led to this problem? (@yuanming-hu have you encountered such kind of errors before? I.e. numerical rounding errors led to NaN..? )

Unfortunately, my understanding of Metal is not enough for me to easily spot where the problem was :( It is even possible that Apple had a poor support on the integrated graphics cards.. (We once observed that Metal's memory order went completely nonsense on an old MBP model)

I could make a patch to disable direct light sampling in this case. The result will be more noisy, but hopefully it can at least present a reasonable result.

**Comment by bobcao3** [comment]
Can not repro, if this is still a issue please reopen
