### ISSUE TITLE
[Bug] Exit() not working correctly

### ISSUE THREAD

**Issue by squarefk** [taichi-dev/taichi#1435]
The following code passed compiled and was supposed to output 'succ'. However, it doesn't.

```
import taichi as ti

ti.init(arch=ti.cpu)


@ti.kernel
def do_something():
    for i in range(100):
        if i < 0:
            exit()
    print("succ")


if __name__ == "__main__":
    do_something()
```

**Comment by yuanming-hu** [comment]
Thanks for reporting this. `exit()` is not supported in Taichi kernel.

**Comment by archibate** [comment]
I'm not surprise with this. Taichi-scope is designed for computation and I/O operations are not supposed.
This is because Taichi codes are passed into a preprocessor and then feed into C++ IR generator. All Python-scope I/O operations will be executed at compile-time.
In fact if you specify `ti.init(print_processed=True)`:
```
Before preprocessing:
@ti.kernel
def do_something():
    for i in range(100):
        if i < 0:
            exit()
    print('succ')

After preprocessing:
def do_something():
  import taichi as ti
  if 1:
    i = ti.Expr(ti.core.make_id_expr(''))
    ___begin = ti.Expr(0)
    ___end = ti.Expr(100)
    ___begin = ti.cast(___begin, ti.i32)
    ___end = ti.cast(___end, ti.i32)
    ti.core.begin_frontend_range_for(i.ptr, ___begin.ptr, ___end.ptr)
    if 1:
      __cond = ti.chain_compare([i, 0], ['Lt'])
      ti.core.begin_frontend_if(ti.Expr(__cond).ptr)
      ti.core.begin_frontend_if_true()
      exit()
      ti.core.pop_scope()
      ti.core.begin_frontend_if_false()
      ti.core.pop_scope()
    ti.core.end_frontend_range_for()
    del i
  ti.ti_print('succ')
```
See? The `for` and `if` is not really the Python ones, they're replaced by our Taichi APIs which is bound using pybind11.
Therefore if exit() occurred, it just stop the compiler, instead of stop in runtime.
