### ISSUE TITLE
Doesn't build with python 3.7 on windows ( error LNK1181 python36.lib )

### ISSUE THREAD

**Issue by daoktar** [taichi-dev/taichi#204]
can't build taichi because of this error:
```bash
       "C:\repo\taichi\build\taichi.sln" (default target) (1) ->
       "C:\repo\taichi\build\taichi_core.vcxproj.metaproj" (default target) (3) ->
       "C:\repo\taichi\build\taichi_core.vcxproj" (default target) (6) ->
       (Link target) ->
         LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\Python37\Lib\site-packages\..\..\libs\pyt
       hon36.lib' [C:\repo\taichi\build\taichi_core.vcxproj]

    520 Warning(s)
    1 Error(s)

Time Elapsed 00:03:28.07
  Error: Build failed.
  Error: installation failed.

```

It seems like its trying to find python lib that is specific to 3.6 version.
I installed python3.6 and everything works fine now.
It will be nice to fix this issue, or put "python 3.6. only" requirement at getting started manual.

**Comment by WenyinWei** [comment]
Hello @daoktar , I met the same bug. The problem arises because the library name is `python3.lib` rather than `python36.lib`. You could have a check of the library folder.

I am also working to find the solution. The key point is to let your compiler know that the python library is the right one.

**Comment by WenyinWei** [comment]
![image](https://user-images.githubusercontent.com/33152225/60954279-4c47a700-a331-11e9-9cc5-917bed19aada.png)

It seems that the bug is caused in cmake but it doesn't appear as a fatal error. I am trying to change a python interpreter to make it.

**Comment by WenyinWei** [comment]
I have succeeded in build `taichi` on Windows. The bug is resolved (in fact just skipped) by changing from Anaconda python interpreter to VS python interpreter. I guess that it would be easy to settle the bug if you could change the python library name specified in the cmake-gui, but I failed because cmake-gui don't accept my specified python library. You could have a try. If not settled ideally, just change an interpreter is the most fast way.
