### ISSUE TITLE
[Bug] incorrect loop indices with mutlilevel structs

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#2177]
**Describe the bug**
Struct for loop indices seem to be wrong when a multilevel struct is used. note that b is placed at the block level, while a is at the leaf level.

**To Reproduce**
```py
import taichi as ti
ti.init(arch=ti.cpu)

a =  ti.field(ti.f32);
b = ti.field(ti.f32);

blocks = ti.root.dense(ti.i, 4)
blocks.place(b)
blocks.dense(ti.i, 4).place(a)

@ti.kernel
def init():
    for i in a:
        a[i] = 1.0
        print(i)

init()

for i in range(4*4):
    assert(a[i] == 1.0)
```

**Log/Screenshots**
I would expect this to print 0 through 15, but it does not. If field b is removed the struct for does print 0 through 15.  Oddly, though, the assert does not trip even though indices look messed up. 
```
[Taichi] mode=development
[Taichi] preparing sandbox at /tmp/taichi-ia11g84x
[Taichi] <dev mode>, llvm 10.0.0, commit 368157a3, linux, python 3.6.9
[Taichi] Starting on arch=x64
[Taichi] materializing...
0
2
3
4
5
1
2
3
1
2
3
4
3
4
5
6

```

There are some differences in the ir when placing b, compared to when it is not placed. 

When placing b:
```
[I 01/27/21 20:44:18.351] [compile_to_offloads.cpp:operator()@19] [init_c4_0] Bit struct stores optimized:
kernel {
  $0 = offloaded range_for(0, 16) grid_dim=0 block_dim=4 
  body {
    <i32> $1 = loop $0 index 0
    <i32> $2 = const [2]
    <i32> $3 = bit_sar $1 $2
    <i32> $4 = const [3]
    <i32> $5 = bit_and $3 $4
    <i32> $6 = bit_and $1 $4
    <i32> $7 = add $5 $6
    <f32> $8 = const [1.0]
    <*gen> $9 = get root
    <i32> $10 = const [0]
    <*gen> $11 = [S0root][root]::lookup($9, $10) activate = false
    <*gen> $12 = get child [S0root->S1dense] $11
    <i32> $13 = bit_and $7 $4
    <*gen> $14 = [S1dense][dense]::lookup($12, $13) activate = false
    <*gen> $15 = get child [S1dense->S3dense] $14
    <*gen> $16 = [S3dense][dense]::lookup($15, $13) activate = false
    <*f32> $17 = get child [S3dense->S4place<f32>] $16
    $18 : global store [$17 <- $8]
    print $7, "\n"
  }
}
```

When not placing b:
```
[I 01/27/21 20:43:43.066] [compile_to_offloads.cpp:operator()@19] [init_c4_0] Bit struct stores optimized:
kernel {
  $0 = offloaded range_for(0, 16) grid_dim=0 block_dim=4 
  body {
    <i32> $1 = loop $0 index 0
    <i32> $2 = const [2]
    <i32> $3 = bit_sar $1 $2
    <i32> $4 = const [3]
    <i32> $5 = bit_and $3 $4
    <i32> $6 = const [4]
    <i32> $7 = mul $5 $6
    <i32> $8 = bit_and $1 $4
    <i32> $9 = add $7 $8
    <f32> $10 = const [1.0]
    <*gen> $11 = get root
    <i32> $12 = const [0]
    <*gen> $13 = [S0root][root]::lookup($11, $12) activate = false
    <*gen> $14 = get child [S0root->S1dense] $13
    <i32> $15 = bit_sar $9 $2
    <i32> $16 = bit_and $15 $4
    <*gen> $17 = [S1dense][dense]::lookup($14, $16) activate = false
    <*gen> $18 = get child [S1dense->S2dense] $17
    <i32> $19 = bit_and $9 $4
    <*gen> $20 = [S2dense][dense]::lookup($18, $19) activate = false
    <*f32> $21 = get child [S2dense->S3place<f32>] $20
    $22 : global store [$21 <- $10]
    print $9, "\n"
  }
}

```

**Comment by k-ye** [comment]
Hi,

Thanks for reporting this! I looked into this, and this was indeed a bug. The difference can be seen from how the IR goes from `root` to `a` layer by layer.

* Without `b`:

```
    <i32> $2 = const [2]
    <i32> $4 = const [3]
    ...
    // goes from ti.root to |blocks|
    <*gen> $14 = get child [S0root->S1dense] $13
    // $9 >> 2
    <i32> $15 = bit_sar $9 $2
    // $15 & 3
    <i32> $16 = bit_and $15 $4
    // goes from |blocks| to |a|'s parent dense
    <*gen> $17 = [S1dense][dense]::lookup($14, $16) activate = false
    <*gen> $18 = get child [S1dense->S2dense] $17
    // $9 & 3
    <i32> $19 = bit_and $9 $4
    // goes from |a|'s parent to |a| itself
    <*gen> $20 = [S2dense][dense]::lookup($18, $19) activate = false
    <*f32> $21 = get child [S2dense->S3place<f32>] $20
```

1. From `root` to `blocks`, the index is `$16 = (($9 >> 2) & 3)`
2. From `blocks` to `a`'s parent `dense`, the index is `$19 = ($9 & 3)`



* With `b`:

```
    <i32> $4 = const [3]
    ...
    // goes from ti.root to |blocks|
    <*gen> $12 = get child [S0root->S1dense] $11
    // $7 & 3
    <i32> $13 = bit_and $7 $4
    <*gen> $14 = [S1dense][dense]::lookup($12, $13) activate = false
    <*gen> $15 = get child [S1dense->S3dense] $14
    <*gen> $16 = [S3dense][dense]::lookup($15, $13) activate = false
```

We can see that for both 1) from `root` to `blocks`, and 2) from `blocks` to `a`'s parent `dense`, the index is `$13 = $7 & 3`, which is wrong.

---

This is caused by how an `SNode`'s covered bit range in each dimension (e.g. `start`, `num_bits`, `acc_offset`) is computed:

https://github.com/taichi-dev/taichi/blob/f904ec3f33f6fc30df830cfacab90a01eaacb9c8/taichi/struct/struct.cpp#L63-L78

When `b` is defined, `b` (a `place` SNode) is the first child of `blocks`. Because a `place` SNode has `0` num_bits, the `extractors[0].start` of `blocks`, i.e. `inferred`, is still `0`.

On the other hand, if `b` is removed, then that `dense(ti.i, 4)` becomes the first child of `blocks`. Because the index of `dense(ti.i, 4)` requires two bits to store, `extractors[0].start` of `blocks` will be `2` this time.

Actually, if you switch the definition order to

```py
blocks.dense(ti.i, 4).place(a)
blocks.place(b)
```

You will get the expected result now. (This is not a correct fix, just to illustrate how things went wrong)

*(Please feel free to ignore this section. This is an implementation detail for us devs to remember what's wrong, and is not meant to be understood by users..)*

---

I don't think Taichi's current implementation could easily solve this problem where the dimensions of an SNode's children are not the same. IIRC, @yuanming-hu  we actually discussed some rules around how the children's dimension can be configured?
