### ISSUE TITLE
Cannot build Taichi in Conda skeleton

### ISSUE THREAD

**Issue by JerryYan97** [taichi-dev/taichi#2189]
**Concisely describe the proposed feature**
For example, when I try to build Taichi in Conda by using the following command
``conda skeleton pypi taichi``
it gives me back the error:
Error: No source urls found for taichi

Does Taichi support conda now?
It looks like Conda Skeleton Requires a source distribution to make it work according to the following post.
https://stackoverflow.com/questions/49735655/conda-skeleton-fails

**Comment by archibate** [comment]
Thank for asking, I'm not sure how Conda manage packages, but currently Taichi **only deploy binary files** to PyPI, and deploy a working source dist could be hard due to its untrivial build steps.
Building Taichi from source requires a lot of dependencies, including LLVM, CUDA, OpenGL... Not to say the LLVM has to be our customized RTTI version (instead of the one officially released by LLVM team).
It's likely these dependencies can't be handled correctly by Conda build steps. Since building Taichi from source really requires a careful setup (we have a [docker image](https://taichi.readthedocs.io/en/stable/dev_install.html#build-the-docker-image) by the way, not sure if Conda support this).
The full step for building Taichi from source is described here:
https://taichi.readthedocs.io/en/stable/dev_install.html

**Comment by JerryYan97** [comment]
Thank you for your reply!

Yeah, I am trying to use conda for Taichi because I want to deploy it on a cluster, which I doesn't have right to totally control the environment or dependency on that machine and I have to set up a virtual environment for everything. 

It would be great if Taichi can be built from Conda directly. I'll check the doc that you give.
Thank you very much!

**Comment by k-ye** [comment]
IIUC, you only want to install `taichi` into your virtual env. If so, could you try the following?

1. Create the virtual env via `conda`, name it `$your_env`
2. `conda activate $your_env`
3. Once `$your_env` is activated, just use `pip install taichi`? But please make sure that `pip` comes from your virtual env. See for example: https://stackoverflow.com/a/43729857/12003165.

**Comment by JerryYan97** [comment]
Hello! 
Thank you for your reply!
Yeah, this is a way that can make it work!
Thank you!
