### ISSUE TITLE
Gaussian random number

### ISSUE THREAD

**Issue by astroyuan** [taichi-dev/taichi#2235]
**Concisely describe the proposed feature**
> Currently the ti.random() function only supports the generation of uniformly distributed random number. Although it's possible to obtain normally distributed random number from it, it will be much more convenient to have a function provides optimized gaussian random number generator.

**Describe the solution you'd like (if any)**
A clear and concise description of what you want to achieve and implement.
I am note sure how to achieve this exactly. I would love to hear any suggestions. 

**Additional comments**
None.

**Comment by yuanming-hu** [comment]
This will be a very useful feature! Maybe we can implement it using `ti.random()` as building blocks. Not sure which algorithm is optimal though: https://www.doc.ic.ac.uk/~wl/papers/07/csur07dt.pdf

It would be nice to thoroughly discuss the implementation plan before coding :-)

**Comment by astroyuan** [comment]
The implementation in [cuRAND](https://developer.nvidia.com/gpugems/gpugems3/part-vi-gpu-computing/chapter-37-efficient-random-number-generation-and-application) might be a useful [reference](https://docs.nvidia.com/cuda/curand/group__HOST.html#group__HOST_1gb9280e447ef04e1dec4611720bd0eb69).
Since I am not familiar with the developing framework, I was naively thinking that using `ti.random()` as a basic uniform random number generator and we just need to design a kernel which does the transformation from the uniform to Gaussian distribution such as [the Box–Muller transform](https://en.wikipedia.org/wiki/Box%E2%80%93Muller_transform), which seems to be a more suitable way to generate Gaussian random number on GPU.

**Comment by archibate** [comment]
Hi, here's how I generate gaussian distributed random number:


```
# https://stackoverflow.com/questions/27229371/inverse-error-function-in-c
@ti.func
def erfinv(x):
&nbsp; &nbsp; sgn = -1 if x < 0 else 1


&nbsp; &nbsp; x = (1 - x) * (1 + x)
&nbsp; &nbsp; lnx = ti.log(x)


&nbsp; &nbsp; tt1 = 2 / (ti.pi * 0.147) + 0.5 * lnx
&nbsp; &nbsp; tt2 = 1 / 0.147 * lnx


&nbsp; &nbsp; return sgn * ti.sqrt(-tt1 + ti.sqrt(tt1**2 - tt2))


@ti.func
def normalrandom():
&nbsp; &nbsp; samp = ti.random()
&nbsp; &nbsp; return ti.sqrt(2) * erfinv(samp * 2 - 1)
```


The erfinv here is not very accurate, but acceptable for my case, which is metrpolis light transport. You may find a iteration version of erfinv in that thread in stackoverflow for better accueracy.
Hope this is helpful to you :)







无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Thu, Mar 25, 2021 23:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [taichi-dev/taichi] Gaussian random number (#2235)




 
The implementation in cuRAND might be a useful reference.
 Since I am not familiar with the developing framework, I was naively thinking that using ti.random() as a basic uniform random number generator and we just need to design a kernel which does the transformation from the uniform to Gaussian distribution such as the Box–Muller transform, which seems to be a more suitable way to generate Gaussian random number on GPU.

**Comment by astroyuan** [comment]
Thanks for the help! In my scenario, I want to generate a large number of independent Gaussian random numbers simultaneously. This method based on [the inverse transformation method](https://en.wikipedia.org/wiki/Inverse_transform_sampling) certainly works.  But I am not sure which method is most suitable in terms of [efficiency and accuracy](https://stats.stackexchange.com/questions/132556/advantages-of-box-muller-over-inverse-cdf-method-for-simulating-normal-distribut). I will use this method for now but it will be great to see a new function such as `ti.random(dist='normal')` which does the job in the future release.
