### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by lanshou** [taichi-dev/taichi#2257]
**Describe the bug**
A clear and concise description of what the bug is, ideally within 20 words.

**To Reproduce**
Please post a **minimal sample code** to reproduce the bug.
The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.

```py
# sample code here
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] mode=release
[Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
...
```

**Additional comments**
If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.

If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.

**Comment by archibate** [comment]
What question do you have? You may edit the content by the instructions in the title so that we can help resolve it.












双笙子佯谬
***@***.***

上海拆桥学院
桥梁爆破小组首席执行官

---Original---
From: ***@***.***&gt;
Date: Mon, Apr 12, 2021 09:48 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [taichi-dev/taichi] testing (#2257)




 
Describe the bug
 A clear and concise description of what the bug is, ideally within 20 words.
 
To Reproduce
 Please post a minimal sample code to reproduce the bug.
 The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code short and representative.
 # sample code here
 
Log/Screenshots
 Please post the full log of the program (instead of just a few lines around the error message, unless the log is &gt; 1000 lines). This will help us diagnose what's happening. For example:
 $ python my_sample_code.py [Taichi] mode=release [Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3 ...  
Additional comments
 If possible, please also consider attaching the output of command ti diagnose. This produces the detailed environment information and hopefully helps us diagnose faster.
 
If you have local commits (e.g. compile fixes before you reproduce the bug), please make sure you first make a PR to fix the build errors and then report the bug.
