### ISSUE TITLE
Accessing 3D ti.field is slow

### ISSUE THREAD

**Issue by ifsheldon** [taichi-dev/taichi#2374]
**Performance Issue**
When I tried a simple kernel that accesses a 3D `ti.field`, the fps seems unreasonably low even if my GPU is NV 3090.  

**To Reproduce**
I think the code is pretty straight forward. The kernel will retrieve a slice of the volume along an axis. I loaded the data into a numpy array whose data will be x-axis first, and y-axis second and z-axis last when it is flattened into a 1D array. 

I tried taking slices from different axes so to check if it's the memory layout issue. It turned out that it is due to memory layout **partially**. I can get ~24 fps when looking along z axis(showing x-y slices), 28 fps when looking along x axis and ~46 fps along y axis. But, 46 fps is still not acceptable since the operations are so simple. The dimensions of my data is `(184, 256, 170)`.

I don't know how you put these data into GPU memory. I was expecting it same as how OpenGL does, which is to put data along x, then y and then z axis. But, from my tests, it seems not to be like this since I cannot get the best fps when looking along z axis.
```python
import taichi as ti
import utils
import numpy as np

ti.init(arch=ti.cuda)
data = utils.load_head_data()  # my helper function that loads a 3D volume
data_f = data / float(np.iinfo(np.uint16).max)  # normalize
width, height, slice_num = data.shape
scaling = 5
data_field = ti.field(ti.f64, shape=(width, height, slice_num))
# try looking from different axis to check memory layout issues
width, height, slice_num = width, slice_num, height
pixels = ti.field(dtype=float, shape=(width * scaling, height * scaling))
# materialization
data_field.from_numpy(data_f)


@ti.kernel
def paint_slice(slice_idx: int):
    for i, j in pixels:
        idx_x = i // scaling
        idx_y = j // scaling
        pixels[i, j] = data_field[idx_x, idx_y, slice_idx]


gui = ti.GUI("SciVis Slicing", res=(width * scaling, height * scaling))
slice_num = int(slice_num)
slice_idx = 3
count = 0
while gui.running:
    paint_slice(slice_idx)
    gui.set_image(pixels)
    gui.show()
    count += 1
    if count % 60 == 0:
        count = 0
        slice_idx += 1
        slice_idx = slice_idx % slice_num

```

**Additional comments**
I'm not a veteran on Taichi, so maybe you know how to tweak to make it much more faster. If so, please tell me and probably update a bit your documentation to record the solution. If you already mentioned similar issues in the documentation and I didn't find them, I apologize in advance.

For the source code and my data if you want to fully test my code, please see my toy [repo](https://github.com/ifsheldon/Differender) and please don't distribute the data. Thanks!

**Comment by archibate** [comment]
a quick answer,&nbsp;what if you replace:
data_field[idx_x, idx_y, slice_idx]
by
data_field[slice_idx,&nbsp;idx_y,&nbsp;idx_x]

?
i.e. use (z, y, x) order instead for the shape of data_field.
this makes memory access pattern preserve more locality, which hopefully may make this memory-bound kernel much faster.







无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Fri, May 28, 2021 21:54 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [taichi-dev/taichi] Accessing 3D ti.field is slow (#2374)




 
Performance Issue
 When I tried a simple kernel that accesses a 3D ti.field, the fps seems unreasonably low even if my GPU is NV 3090.
 
To Reproduce
 I think the code is pretty straight forward. The kernel will retrieve a slice of the volume along an axis. I loaded the data into a numpy array whose data will be x-axis first, and y-axis second and z-axis last when it is flattened into a 1D array.
 
I tried taking slices from different axes so to check if it's the memory layout issue. It turned out that it is due to memory layout partially. I can get ~24 fps when looking along z axis(showing x-y slices), 28 fps when looking along x axis and ~46 fps along y axis. But, 46 fps is still not acceptable since the operations are so simple. The dimensions of my data is (184, 256, 170).
 
I don't know how you put these data into GPU memory. I was expecting it same as how OpenGL does, which is to put data along x, then y and then z axis. But, from my tests, it seems not to be like this since I cannot get the best fps when looking along z axis.
 import taichi as ti import utils import numpy as np ti.init(arch=ti.cuda) data = utils.load_head_data()  # my helper function that loads a 3D volume data_f = data / float(np.iinfo(np.uint16).max)  # normalize width, height, slice_num = data.shape scaling = 5 data_field = ti.field(ti.f64, shape=(width, height, slice_num)) # try looking from different axis to check memory layout issues width, height, slice_num = width, slice_num, height pixels = ti.field(dtype=float, shape=(width * scaling, height * scaling)) # materialization data_field.from_numpy(data_f) @ti.kernel def paint_slice(slice_idx: int):     for i, j in pixels:         idx_x = i // scaling         idx_y = j // scaling         pixels[i, j] = data_field[idx_x, idx_y, slice_idx] gui = ti.GUI("SciVis Slicing", res=(width * scaling, height * scaling)) slice_num = int(slice_num) slice_idx = 3 count = 0 while gui.running:     paint_slice(slice_idx)     gui.set_image(pixels)     gui.show()     count += 1     if count % 60 == 0:         count = 0         slice_idx += 1         slice_idx = slice_idx % slice_num
 
Additional comments
 I'm not a veteran on Taichi, so maybe you know how to tweak to make it much more faster. If so, please tell me and probably update a bit your documentation to record the solution. If you already mentioned similar issues in the documentation and I didn't find them, I apologize in advance.
 
For the source code and my data if you want to fully test my code, please see my toy repo and please don't distribute the data. Thanks!

**Comment by k-ye** [comment]
HI,

There are two factors here:

1.Taichi's current implementation pads shape to power-of-two internally. So when you visualize x-y plane, the internal shape of `pixels` is actually (1024, 2048).
2. Taichi has to copy pixels from CUDA to CPU every time GUI gets re-drawed.

The simplest fix for 1 might be to copy only the effective data range (i.e., the first 5x184x5x256 floats). https://github.com/taichi-dev/taichi/issues/2344 somewhat points to a similar issue. For 2, you can initialize the `GUI` object with the `fast_gui` option. Here's the modified code looping along the z-axis:

```py
import taichi as ti
import utils
import numpy as np

ti.init(arch=ti.cuda)
# ...
pixels = ti.Vector.field(3, dtype=float, shape=(width * scaling, height * scaling))
# materialization
data_field.from_numpy(data_f)


@ti.kernel
def paint_slice(slice_idx: int):
    for i, j in pixels:
        idx_x = i // scaling
        idx_y = j // scaling
        pixels[i, j].fill(data_field[idx_x, idx_y, slice_idx])


gui = ti.GUI("SciVis Slicing", res=(width * scaling, height * scaling), fast_gui=True)
while gui.running:
    paint_slice(slice_idx)
    gui.set_image(pixels)
    gui.show()
    # ...
```

**Comment by ifsheldon** [comment]
Despite these modifications work, can you please explain more on why we use `ti.Vector.field` here and what `fast_gui` here does? I did not find the doc about `fast_gui`.

**Comment by k-ye** [comment]
> Despite these modifications work, can you please explain more on why we use `ti.Vector.field` here and what `fast_gui` here does? I did not find the doc about `fast_gui`.
> 
> 
> 
> Also, can you explain more on why we don't get the best performance when we slice the volume along z-axis? I was expecting the data layout should be the same as OpenGL textures. And I think this issue has nothing related to the changes that you made in order to address the GUI issue.

Note that your volume shape is (184, 256, 170). Slicing along the z-axis means your canvas (`pixels`) takes the larger two dimensions. And the larger the canvas it is, the more data it takes to copy GPU <-> CPU and CPU <-> CPU.

`fast_gui` reduces one such copy on the CPU. In order to do so, the field must be exactly in RGB or RGBA format. Therefore Vec3.

Taichi layouts out data in k-j-i order. You can try to bring the slice index to the first dimension to see if there's a difference. (But it seems that excessive copying is the major bottleneck here)

**Comment by ifsheldon** [comment]
OK, thanks a lot! I suggest you update a bit in the documentation on `fast_gui`.

**Comment by k-ye** [comment]
PTAL https://github.com/taichi-dev/taichi/pull/2385 @ifsheldon
