### ISSUE TITLE
taichi example missing

### ISSUE THREAD

**Issue by gwoweiming** [taichi-dev/taichi#2588]
[Taichi] version 0.7.26, llvm 10.0.0, commit e37bdb5e, win, python 3.9.6

taichi examples only have {minimal}

**Comment by k-ye** [comment]
Oops, this is because of https://github.com/taichi-dev/taichi/pull/2475. For now you can directly execute these examples w/ `python3 $EXAMPLE_NAME`. @victoriacity could you help take a look around https://github.com/taichi-dev/taichi/blob/fbc1f43db67de7e29b2b94b396b1c6c6b4c40d74/python/taichi/main.py#L152-L153 ?

**Comment by victoriacity** [comment]
It looks like the example subfolders are missing in the PyPI distribution, while in the GitHub release the examples are present.

I guess it would be related to the `ti dist` scripts and I'm looking into this.
