### ISSUE TITLE
examples math_utils: rand_vector(n) broken, 'Expr' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by EricCousineau-TRI** [taichi-dev/taichi#2617]
**Describe the bug**
`tree_gravity.py` example seems broken, I get an error here:
https://github.com/taichi-dev/taichi/blob/7a2d5d11d4d03d0d306e1a1c4a131ef65b8e5232/examples/simulation/tree_gravity.py#L132-L134

**To Reproduce**
```sh
$ cd taichi
$ git log -n 1 --oneline --no-decorate
7a2d5d11 [Lang] [refactor] Move SNode property calculation from materialization time to construction time (#2600)
$ python3 -m venv ./venv
$ source ./venv/bin/active
$ pip install -U pip wheel
$ pip install taichi==0.7.26  # I think this is sufficient
$ python3 examples/simulation/tree_gravity.py
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-u3n9wd_j
[Taichi] version 0.7.26, llvm 10.0.0, commit e37bdb5e, linux, python 3.6.9
[Taichi] Starting on arch=x64
...
# Click on GUI
Traceback (most recent call last):
...
  File "./tree_gravity.py", line 135, in add_particle_at
    rand_vec = rand_vector(2)
  File ".../taichi/venv_prebuilt/lib/python3.6/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File ".../taichi/venv_prebuilt/lib/python3.6/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File ".../taichi/examples/simulation/math_utils.py", line 11, in rand_vector
    return ti.Vector([ti.random() for _ in range(n)])
TypeError: 'Expr' object cannot be interpreted as an integer
```

**Log/Screenshots**
See above

**Additional comments**
It works if I just inline the logic for `rand_vector()`, or manually expand, i.e.:
```py
# rand_vec = rand_vector(2)  # Does not work (see above)
rand_vec = ti.Vector([ti.random() for _ in range(2)])  # Works
rand_vec = ti.Vector([ti.random(), ti.random()]  # Works
```

**Comment by EricCousineau-TRI** [comment]
Also fails w/ same source tree as prebuilt binary
```
$ git log -n 1 --oneline --no-decorate
e37bdb5e [release] v0.7.26 (#2511)
```

**Comment by victoriacity** [comment]
Removing the `@ti.func` decorator on the `rand_vector()` function solves the problem, see https://github.com/victoriacity/taichi/blob/fix-2617/examples/simulation/math_utils.py.

With `ti.init(print_preprocessed=True)`, not having the `@ti.func` decorator will prevent the variable `n` be preprocessed into a Taichi `Expr` so that it can be used in list comprehension.

**Comment by EricCousineau-TRI** [comment]
Nice! This seems like a minor bug in how @ti.func` transformations are done - is there any mitigation possible?
(or should it just be briefly mentioned in the docs? e.g. "Taichi functions can be nested, but with some nuance [...]" https://taichi.readthedocs.io/en/stable/syntax.html#functions)

**Comment by xumingkuan** [comment]
I think the problem is that, list comprehension (Python lists with `[elt for target in iter]` syntax) requires the object to iterate over (`iter` here) to be *compile-time constant* in Taichi, and `n` in `def rand_vector(n):` in math_utils.py is not a compile-time constant in Taichi.

I would suggest a solution that is simply rewrite the function signature as `def rand_vector(n: ti.template()):`, so that Taichi would treat `n` as a template parameter, which is a compile-time constant. Invocations with different `n` of this function will be treated as different functions.

As suggested by @victoriacity, using a Python function instead of a Taichi function also works for this case. But if the same bug happens on a Taichi function with control flows (`def rand_vector(n):` does not have control flows), using `ti.template()` is probably the best choice :)

**Comment by xumingkuan** [comment]
We should mention in the docs that list comprehensions and dictionary comprehensions require that:
- the object to iterate over is a compile-time constant;
- the target is not a Taichi field's component;
- the "ifs" (if exist) are compile-time constants when the target is a compile-time constant.

E.g., `[x[0] for j in range(100) if j > 2 if j < 5]` is a valid list comprehension because `range(100)` is a compile-time constant, `j` is not a Taichi field's component, `j > 2` and `j < 5` are compile-time constants when `j` is a compile-time constant.
