### ISSUE TITLE
Add more complicated tests for building and destroying SNodeTree.

### ISSUE THREAD

**Issue by beginlner** [taichi-dev/taichi#2724]
https://github.com/taichi-dev/taichi/blob/63140f6fa56322c5af606662a60f48cb50acea2b/tests/python/test_fields_builder.py#L134

**Comment by ysh329** [comment]
I would like to help!

**Comment by k-ye** [comment]
Hi @ysh329 , those docs are pretty helpful. In addition, you might want to look at these:

* https://docs.taichi.graphics/lang/articles/contribution/dev_install (if you haven't already built Taichi)
* https://docs.taichi.graphics/lang/articles/contribution/write_test

As for the field, we can start simple and see what happens if you read/write field `a` after `c` gets destroyed: https://github.com/taichi-dev/taichi/blob/63140f6fa56322c5af606662a60f48cb50acea2b/tests/python/test_fields_builder.py#L138-L141

**Comment by lucywsq** [comment]
Hi, @ysh329 if you're working on this issue, please let us know, thanks!

**Comment by ysh329** [comment]
@lucywsq OK

**Comment by ysh329** [comment]
Currently my dev env. is okay and unit test run okay like below:

```shell
++ python3 -m taichi test
[Taichi] version 0.8.3, llvm 10.0.0, commit 27bb1dc3, linux, python 3.9.5

*******************************************
**      Taichi Programming Language      **
*******************************************

Docs:   https://docs.taichi.graphics/
GitHub: https://github.com/taichi-dev/taichi/
Forum:  https://forum.taichi.graphics/


Running Python tests...

Starting 8 testing thread(s)...
========================================= test session starts ==========================================
platform linux -- Python 3.9.5, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/stayua01/code/taichi
plugins: xdist-2.4.0, forked-1.3.0, rerunfailures-10.2, cov-3.0.0
gw0 [1119] / gw1 [1119] / gw2 [1119] / gw3 [1119] / gw4 [1119] / gw5 [1119] / gw6 [1119] / gw7 [1119]
【IGNORED】
```

I found if I run single file like below:

```shell
(base) stayua01@100013000760:~/code/taichi$ python tests/python/test_fields_builder.py
[Taichi] version 0.8.3, llvm 10.0.0, commit 27bb1dc3, linux, python 3.9.5
[W 11/02/21 09:24:21.481 11647] [cuda_driver.cpp:CUDADriver@38] CUDA driver not found.
```

It doesn't any tips about current backend such as cpu.

**Comment by ysh329** [comment]
I think this issue can be closed, please ensure @lucywsq

**Comment by ailzhang** [comment]
Thanks @ysh329 ! Closing via #3415
