### ISSUE TITLE
How to  use @ with a single Matrix and Vector fields

### ISSUE THREAD

**Issue by liyou54** [taichi-dev/taichi#2864]
Like Question

![image](https://user-images.githubusercontent.com/33220619/131688507-58f9733c-1a7e-4ae6-a667-7cd849fbc8e8.png)

![image](https://user-images.githubusercontent.com/33220619/131688646-b85f085b-1ee7-4800-8306-8fc7581ee97a.png)

**Comment by liyou54** [comment]
![image](https://user-images.githubusercontent.com/33220619/131688961-e4d2eede-2519-4cf7-86ee-4944c54209a2.png)

**Comment by squarefk** [comment]
If I understand correctly, `self.vertices` and `self.res` are two 1-D fields where each element is a vector.
Fields doesn't support operations like `@`. You need to compute only with vectors like the following:
```
import taichi as ti

ti.init(arch=ti.cpu, print_preprocessed=True)

Matrix_M = ti.Matrix([[1.,1.],[1.,1.]], dt=ti.f32)
res = ti.Vector.field(2, dtype=ti.f32, shape=(100))
vertices = ti.Vector.field(2, dtype=ti.f32, shape=(100))

@ti.kernel
def my_kernel():
    for I in ti.grouped(vertices):
        res[I] = Matrix_M @ vertices[I]

my_kernel()
```
Also, you might want to change Matrix_M's definition to use `1.` instead of `1` to indicate the actual type.
