### ISSUE TITLE
Simplify `ti.Matrix`

### ISSUE THREAD

**Issue by strongoier** [taichi-dev/taichi#2880]
Currently `ti.Matrix` has become a single class with more than 1000 lines, with all deprecated/obsolete/unused/rarely used features mixed together. For better code maintainability, we need to carefully decide what should be exposed to users and clean up this class.

**Comment by victoriacity** [comment]
I'd recommend moving the linear algebra methods (`inverse()`, `diag()`, `determinant()`) to `linalg.py` so that we have a clear distinction between API and math implementations. Then `Matrix.inverse()` and similar methods will become an alias of `ti.inverse()`, similar to NumPy ndarrays and PyTorch tensors.
