### ISSUE TITLE
Error popped up when running IRBuilder tests

### ISSUE THREAD

**Issue by BillXu2000** [taichi-dev/taichi#3636]
**Describe the bug**
Error popped up when running IRBuilder tests.
Taichi version: commit fdf665e4dfe6c1cee41e67b12b288749b2c8cb8f

**To Reproduce**

```bash
TAICHI_CMAKE_ARGS="-DTI_WITH_VULKAN=ON -DTI_EXPORT_CORE=ON -DTI_BUILD_TESTS=ON" python3 setup.py develop --user
build/taichi_cpp_tests --gtest_filter="IRBuilder.ExternalPtr"
```

**Log/Screenshots**

```
Note: Google Test filter = IRBuilder.ExternalPtr
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from IRBuilder
[ RUN      ] IRBuilder.ExternalPtr
[E 11/29/21 11:16:57.803 1866558] [jit_cpu.cpp:lookup_in_module@177] Function "runtime_memory_allocate_aligned" not found


Expected<T> must be checked before access or destruction.
Unchecked Expected<T> contained error:
```

**Comment by strongoier** [comment]
According to https://docs.taichi.graphics/lang/articles/contribution/writing_cpp_tests#build-and-run-taichi-c-tests, you have to set `TI_LIB_DIR`.

**Comment by BillXu2000** [comment]
It turns out that my local Taichi environment was too messy.
Problem is fixed now after I cleaned up and reinstalled Taichi.

**Comment by quadpixels** [comment]
I ran into this again on a Windows 10 box today, with `TI_LIB_DIR` already set correctly.
The fix for the IRBuilder test to be able to run is to copy `taichi\build\lib.win-amd64-3.7\taichi\_lib\runtime` to `taichi\python\taichi\lib`. I reckon my build folder is also quite a few months old so doing a clean-up and reinstalling might also be able to fix this issue. Now `taichi_cpp_tests.exe` can run correctly.
