### ISSUE TITLE
AttributeError: module 'taichi' has no attribute 'var'

### ISSUE THREAD

**Issue by wang850228803** [taichi-dev/taichi#364]
I use ubutnu16.04.

I installed taichi using command:
`python3 -m pip install taichi-nightly`

And installing Taichi Library using command:
```
wget https://raw.githubusercontent.com/yuanming-hu/taichi/legacy/install.py
python3 install.py
``` 

And set the environment path:
```
export TAICHI_REPO_DIR=/home/wanghui/code/taichi-etc/taichi
export PYTHONPATH=TAICHI_REPO_DIR/python/:$PYTHONPATH
```

But when i run the example fractal.py:
```
[T 01/09/20 17:01:52.987] [logging.cpp:Logger@67] Taichi core started. Thread ID = 8648
Traceback (most recent call last):
  File "fractal.py", line 4, in <module>
    pixels = ti.var(dt=ti.f32, shape=(n * 2, n))
AttributeError: module 'taichi' has no attribute 'var'
```
Anything wrong?

**Comment by yuanming-hu** [comment]
Hi,

`python3 -m pip install taichi-nightly` is all you need.

Please remove your taichi repo and env variables - they will fight against pip.

**Comment by WSFeng** [comment]
> Hi,
> 
> `python3 -m pip install taichi-nightly` is all you need.
> 
> Please remove your taichi repo and env variables - they will fight against pip.

> export TAICHI_NUM_THREADS=8
> export TAICHI_REPO_DIR=/Users/XXXX/Documents/Taichi/taichi
> export PYTHONPATH=$TAICHI_REPO_DIR/python/:$PYTHONPATH
> export PATH=$TAICHI_REPO_DIR/bin/:$PATH

remove what?

**Comment by yuanming-hu** [comment]
Please remove all four env vars.

**Comment by wang850228803** [comment]
Share my experience here:
Environment: ubutnu16.04
Steps:
1. upgrade python3.5 to python3.7.
2. Download taichi_nightly-0.3.20-cp37-cp37m-manylinux1_x86_64.whl from https://pypi.org/project/taichi-nightly/#files
(pip3 install can not install the latest version, so use this method)
3. pip3 install taichi_nightly-0.3.20-cp37-cp37m-manylinux1_x86_64.whl
4. python3 fractal.py
 Errors:
_[Release mode]
Traceback (most recent call last):
  File "fractal.py", line 1, in <module>
    import taichi as ti
  File "/usr/local/lib/python3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/usr/local/lib/python3.7/site-packages/taichi/main.py", line 6, in <module>
    from taichi.tools.video import make_video, interpolate_frames, mp4_to_gif, scale_video, crop_video, accelerate_video
  File "/usr/local/lib/python3.7/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/usr/local/lib/python3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, load_module, start_memory_monitoring, \
  File "/usr/local/lib/python3.7/site-packages/taichi/core/util.py", line 158, in <module>
    import_tc_core()
  File "/usr/local/lib/python3.7/site-packages/taichi/core/util.py", line 31, in import_tc_core
    import taichi_core as core
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so)_

Seem that CXXABI's  is not satisfied. So I give up Ubuntu. Using Mac.
Mac is so easy.
Just the command below is OK.
`_python3 -m pip install taichi-nightly`
`python3 fractal.py_`

**Comment by dongYzzz** [comment]
Traceback (most recent call last):
  File "ice.py", line 3, in <module>
    ti.init(arch=ti.cuda) # Try to run on GPU
AttributeError: module 'taichi' has no attribute 'init'

how to solve this ?

**Comment by LareinaM** [comment]
> Traceback (most recent call last):
> File "ice.py", line 3, in 
> ti.init(arch=ti.cuda) # Try to run on GPU
> AttributeError: module 'taichi' has no attribute 'init'
> 
> how to solve this ?

Did you name the file as taichi?

**Comment by archibate** [comment]
> Traceback (most recent call last):
> File "ice.py", line 3, in 
> ti.init(arch=ti.cuda) # Try to run on GPU
> AttributeError: module 'taichi' has no attribute 'init'
> 
> how to solve this ?

Could you try run
`print(__import__('taichi').__file__)`?

**Comment by JackyWang2001** [comment]
Hi, I am having the same issue on macOS Monterey 12.4 (MacBook Pro 2018) with the latest Taichi 
```
python fractal.py
[Taichi] version 1.0.2, llvm 10.0.0, commit 14f0acba, osx, python 3.8.0
[Taichi] Starting on arch=metal
Traceback (most recent call last):
  File "fractal.py", line 6, in <module>
    pixels = ti.var(dt=ti.f32, shape=(n * 2, n))
  File "/Users/jacky/anaconda3/envs/cg/lib/python3.8/site-packages/taichi/__init__.py", line 82, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{attr}'")
AttributeError: module 'taichi' has no attribute 'var'
```
I also tried Taichi-nightly 0.5.11 on my laptop and repeated the steps on a borrowed macOS Monterey 12.3 but the same error is still there (so I doubt probably because of the system?). 

Could you give any suggestions on this?
Thank you

**Comment by archibate** [comment]
Your fractal.py is too old to run on latest Taichi. AFAIK&nbsp;Taichi v1.0 already deprecated ti.var. Please download the latest fractal.py on github to replace it.











无法顺畅的大口呼吸，是活着的最好证明

---Original---
From: ***@***.***&gt;
Date: Sun, May 29, 2022 09:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [taichi-dev/taichi] AttributeError: module 'taichi' has no attribute 'var' (#364)




 
Hi, I am having the same issue on macOS Monterey 12.4 (MacBook Pro 2018) with the latest Taichi
 python fractal.py [Taichi] version 1.0.2, llvm 10.0.0, commit 14f0acba, osx, python 3.8.0 [Taichi] Starting on arch=metal Traceback (most recent call last):   File "fractal.py", line 6, in <module&gt;     pixels = ti.var(dt=ti.f32, shape=(n * 2, n))   File "/Users/jacky/anaconda3/envs/cg/lib/python3.8/site-packages/taichi/__init__.py", line 82, in __getattr__     raise AttributeError(f"module '{__name__}' has no attribute '{attr}'") AttributeError: module 'taichi' has no attribute 'var'  
I also tried Taichi-nightly 0.5.11 on my laptop and repeated the steps on a borrowed macOS Monterey 12.3 but the same error is still there (so I doubt probably because of the system?).
 
Could you give any suggestions on this?
 Thank you
