### ISSUE TITLE
Low python version for pylint job in CI

### ISSUE THREAD

**Issue by lin-hitonami** [taichi-dev/taichi#4008]
**Describe the bug**
The python version for the pylint job is 3.8. So, when I use a function that is introduced in 3.9, it produces the following error.

```
python/taichi/lang/ast/ast_transformer.py:371:31: E1101: Module 'ast' has no 'unparse' member (no-member)
```

**Comment by lin-hitonami** [comment]
maybe cc @frostming

**Comment by frostming** [comment]
It is not enough to make linter happy. Because taichi is expected to work on Python >= 3.6, we should make it compatible with all promised python versions.

For Python < 3.9, we need a backport of that function, there are two candidates:
- [astunparse](https://pypi.org/project/astunparse/), [github](https://github.com/simonpercivall/astunparse)
- [ast_compat](https://pypi.org/project/ast-compat/), [github](https://pypi.org/project/ast-compat/)

I didn't dig too deep, both are adapted from the CPython source, but there might be slight differences. You can try both to see if they work fine on older Python versions.

Use a compatibility code like the following:

```python
if sys.version_info >= (3, 9):
    ast_unparse = ast.unparse
else:
    from astunparse import unparse as ast_unparse
```

**Comment by lin-hitonami** [comment]
> 

I've already wrapped it in `if sys.version_info >= (3, 9):` but it is also not happy.
Btw, thanks for the candidate.

**Comment by frostming** [comment]
If the compatibility is guaranteed, then run linter with higher python is an option.
