### ISSUE TITLE
Accessing 0-D Tensors: `x[None]` or `x.item`?

### ISSUE THREAD

**Issue by jackalcooper** [taichi-dev/taichi#415]
**Is your feature request related to a problem? Please describe.**
`[None]` is confusing and ambiguous.

**Describe the solution you'd like**
impl a `item` method like [item in pytorch](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.item) and [item in numpy](https://docs.scipy.org/doc/numpy-1.17.0/reference/generated/numpy.ndarray.item.html#numpy.ndarray.item)

**Comment by yuanming-hu** [comment]
Thanks for the proposal. I agree with you that `x[None]` is weird, but it unifies tensor element read and write. Although you can probably implement `x.item()` for reading a 0-D tensor, but you can't assign to a function call in Python. I.e. `x.itme() = 3` is not parsable by the Python parser. We need more discussion on this.

**Comment by archibate** [comment]
Why not define `item` as a get/set method?
```python
class Tensor:
    @property
    def item(self):
        return self[None]

    @item.setter
    def item(self, value):
        self[None] = value
```
So that you can use `x.item = 233` to assign and `value = x.item` to read at the same time.

**Comment by yuanming-hu** [comment]
@archibate I think `x.item` is a clever solution, but personally I would still prefer keeping the old `x[None]` solution, because it follows the `bracket + index` pattern, just as non-scalar tensors (e.g. `y[1, 42, 64]`). This makes dimensionality-independent programming easier. For example, you can literally do https://github.com/taichi-dev/taichi/blob/1ca769de3f6b64182ed0911c04767e9838f24b0f/tests/python/test_struct_for.py#L11

We can implement `x.item` (or `x.value`) as well, since it's more readable for new-comers. However, having two different ways to do one thing might further add to the confusion.

What do you guys think? @k-ye  @KLozes @jackalcooper Inputs are welcome :-)

**Comment by KLozes** [comment]
I personally prefer x[None]. Btw, x[()] seems to work too. Sadly, x[] doesn't work even if you make None the default input for __setitem__ and __getitem__.

**Comment by yuanming-hu** [comment]
> I personally prefer x[None]. Btw, x[()] seems to work too. Sadly, x[] doesn't work even if you make None the default input for setitem and getitem.

Yeah I guess a perfect solution doesn't exist right now. Let's stick to `x[None]`.
