### ISSUE TITLE
ti.deactivate not zeroing data before recycling

### ISSUE THREAD

**Issue by KLozes** [taichi-dev/taichi#427]
**Describe the bug**
ti.deactivate appears to not be zeroing out data before recycling. This causes later the newly activated elements to possibly be non-zero. 

**Log/Screenshots**
The script below triggers the assert

**To Reproduce**
```python
import taichi as ti

real = ti.f32
ti.get_runtime().set_default_fp(real)
ti.cfg.arch = ti.x86_64
#ti.cfg.arch = ti.cuda

a = ti.var(dt=real)

@ti.layout
def layout():
  ti.root.dense(ti.i, 8).pointer().dense(ti.i,8).place(a)


@ti.kernel
def fill():
  for i in range(8*8):
    a[i] = 1.0

@ti.kernel
def clear():
  for i in a.parent().parent():
    ti.deactivate(a.parent().parent(),i)

@ti.kernel
def set10():
  a[10] = 10.0

fill()
clear()
set10()
for i in range(8*8):
  #print(a[i])
  assert(a[i] != 1.0)
```

**Comment by yuanming-hu** [comment]
Thanks for reporting! I haven't got much time to fully test the sparse operations, since I've been optimizing a few other constructs. I'll work on this one very soon. Please make a PR with this test case (with a `return` at the very beginning of the test so that it will get skipped and not annoy our buildbots, until someone explicitly enables it for bug fixing.)

**Comment by yuanming-hu** [comment]
Bug fixed. I didn't set `element_size` for `NodeManager`, so this value ends up being `0` and during GC the manager simply zero-fills elements of size `0` bytes. Thus the bug you found. Thanks for reporting this!

**Comment by yuanming-hu** [comment]
(Also note that this part lacks testing and performance optimization. I'm working on optimizing it right now.)
