### ISSUE TITLE
[Docs] It might be clearer to move updates to a standalone changelog

### ISSUE THREAD

**Issue by rexwangcc** [taichi-dev/taichi#449]
**Concisely describe the proposed feature**
It will make the readme cleaner if the updates section can be moved to a changelog file in the root dir. 

**Describe the solution you'd like**
- Move the updates section from readme to a changelog file in the root dir. 

**Additional comments**
- Currently, there are some key features and gifs in the updates section, I assume, for showcase purposes, which could be kept and merged to examples section.

**Comment by yuanming-hu** [comment]
Thanks for the feedback. Following your suggestion, I moved old updates before v0.4.0 to a standalone `changelog.md`. I think it's good to have some most recent updates on the frontpage so that people see it.

I plan to add more visual demos (gifs) next week, ideally before the "Contributor Guide" link.

**Comment by rexwangcc** [comment]
@yuanming-hu It looks clean and concise, and it definitely makes sense to keep a short list of recent changes in the main readme. Thanks for the prompt reply. I'm closing this issue :octocat:
