### ISSUE TITLE
Would you consider to decouple frontend from backends?

### ISSUE THREAD

**Issue by stamnug** [taichi-dev/taichi#4518]
Taichi is responsible for maintaining a c++ ast of Taichi and publishing a interface about Kernel_impl. 
user is able to implements any frontend by construct a Kernel_impl with c++ ast.

**Comment by AmesingFlank** [comment]
This is already possible to some extent. The user can use the C++ CHI IR builder to build a non-python frontend. As an example, I built [taichi.js](https://amesingflank.github.io/taichi.js/zoo/index.html) using this approach.

It would indeed be more convenient if one can use a unified AST builder instead of the IR builder. And we do hope that in the future, the C++ AST will become powerful enough that new frontends can simply do AST-to-AST translations. This will require a lot of work (type checking and inference on C++ ASTs) and we'd greatly appreciate any contributions.

**Comment by stamnug** [comment]
CHI IR level is ok too, maybe taichi is able to be splited to two project about frontend and backend respectively . and virtualize a part of kernel funtion. user is able to use taichi as long as user inherit kernel and implement virtual funtion
