### ISSUE TITLE
broken documentation link on taichi.graphics

### ISSUE THREAD

**Issue by yhesper** [taichi-dev/taichi#4723]
**Describe the bug**
Broken documentation link on [taichi.graphics](https://taichi.graphics/)

**To Reproduce**
Click the "Documentation" button on [taichi.graphics](https://taichi.graphics/)

**Comment by Vissidarte-Herman** [comment]
Thanks. I'm on it.

**Comment by rexwangcc** [comment]
Hi, thanks for reporting!! Since we have revamped the website a while ago and have been experiencing caching issues along the time, just to make sure you are seeing the following (new) page via [taichi.graphics](https://taichi.graphics/)? (if not, maybe you would have to use incognito mode or clear your browser cache 😄 )

<img width="1277" alt="Screen Shot 2022-04-06 at 8 15 40 PM" src="https://user-images.githubusercontent.com/14366016/161972643-b5307bec-4acd-4e35-9a45-83142eff1bc6.png">

**Comment by yhesper** [comment]
> Hi, thanks for reporting!! Since we have revamped the website a while ago and have been experiencing caching issues along the time, just to make sure you are seeing the following (new) page via [taichi.graphics](https://taichi.graphics/)? (if not, maybe you would have to use incognito mode or clear your browser cache 😄 )
> 
> <img alt="Screen Shot 2022-04-06 at 8 15 40 PM" width="1277" src="https://user-images.githubusercontent.com/14366016/161972643-b5307bec-4acd-4e35-9a45-83142eff1bc6.png">

I see, I was viewing the old page! Damn, browser cache strikes again lol

**Comment by knight42** [comment]
@yhesper Hi! Please clear your brower cache or follow the instructions in https://answers.netlify.com/t/support-guide-understanding-unregistering-service-workers/145 to disable service worker to see if you could view the new page.

Please feel free to reopen this issue if there are other problems.
