### ISSUE TITLE
Taichi doesn't compile to Pyinstaller

### ISSUE THREAD

**Issue by compik710** [taichi-dev/taichi#4936]
Hello! I have a problem with taichi compilling.

I am trying to compile this code example from the docs https://docs.taichi.graphics/
```py
import taichi as ti

ti.init(arch=ti.gpu)

n = 320
pixels = ti.field(dtype=float, shape=(n * 2, n))

@ti.func
def complex_sqr(z):
    return ti.Vector([z[0]**2 - z[1]**2, z[1] * z[0] * 2])

@ti.kernel
def paint(t: float):
    for i, j in pixels:  # Parallelized over all pixels
        c = ti.Vector([-0.8, ti.cos(t) * 0.2])
        z = ti.Vector([i / n - 1, j / n - 0.5]) * 2
        iterations = 0
        while z.norm() < 20 and iterations < 50:
            z = complex_sqr(z) + c
            iterations += 1
        pixels[i, j] = 1 - iterations * 0.02

gui = ti.GUI("Julia Set", res=(n * 2, n))

i = 0
while gui.running:
    paint(i * 0.03)
    gui.set_image(pixels)
    gui.show()
    i = i + 1
```

with command
`pyinstaller taichi_test5.py -F -n Taichi_test`

and when i run the compiled file i get the following error:
```
$cd dist
$./Taichi_test
[Taichi] version 1.0.1, llvm 10.0.0, commit 1c3619d9, linux, python 3.10.4
[W 05/09/22 16:20:54.893 26927] [cuda_driver.cpp:CUDADriver@38] CUDA driver not found.
[Taichi] Starting on arch=opengl
Traceback (most recent call last):
  File "sourceinspect/__init__.py", line 150, in our_findsource
  File "inspect.py", line 958, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sourceinspect/__init__.py", line 96, in blender_findsourcetext
ModuleNotFoundError: No module named 'bpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sourceinspect/__init__.py", line 153, in our_findsource
  File "sourceinspect/__init__.py", line 110, in blender_findsource
  File "sourceinspect/__init__.py", line 98, in blender_findsourcetext
OSError: Not in Blender environment!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sourceinspect/__init__.py", line 156, in our_findsource
  File "sourceinspect/__init__.py", line 42, in remote_findsource
  File "sourceinspect/__init__.py", line 28, in remote_findsourcelines
OSError: Cannot find file /tmp/SI_IPC_26927.py!
To make Taichi functional in IDLE, please append the following line:

__import__("sourceinspect").remote_hack(globals())

to file "/tmp/_MEIqNYs1Y/code.pyc".


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sourceinspect/__init__.py", line 159, in our_findsource
  File "sourceinspect/__init__.py", line 145, in dill_findsource
  File "dill/source.py", line 154, in findsource
OSError: could not extract source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "taichi_test5.py", line 27, in <module>
  File "taichi/lang/kernel_impl.py", line 816, in wrapped
  File "taichi/lang/kernel_impl.py", line 746, in __call__
  File "taichi/lang/kernel_impl.py", line 733, in ensure_compiled
  File "taichi/lang/kernel_impl.py", line 494, in materialize
  File "taichi/lang/kernel_impl.py", line 107, in _get_tree_and_ctx
  File "sourceinspect/__init__.py", line 193, in getsourcelines
  File "inspect.py", line 1129, in getsourcelines
  File "sourceinspect/__init__.py", line 161, in our_findsource
OSError: Could not get source code for object: <function paint at 0x7fa665a43b50>
[26927] Failed to execute script 'taichi_test5' due to unhandled exception!
```

Anyone have experience with this? Thank you!

**Comment by neozhaoliang** [comment]
I guess this is because the compiled code cannot handle GPU resources? @ailzhang Could help have a look at this?

**Comment by ailzhang** [comment]
@compik710 This happens due to taichi failed to find the source code for `paint` function. I'm not very familiar with  pyinstaller, two quick questions:
- Does it work if you run the script using `python` directly? 
If it works this might be related how pyinstaller packages a python script and its dependency hmmm

**Comment by compik710** [comment]
@ailzhang  yes it works directly. However, now I think I don't need to use pyinstaller as it's easier and faster to install Taichi on my computer. Thanks for the answer

**Comment by compik710** [comment]
Who read it, you can try this:
```
pyinstaller taichi_test5.py -F -n Taichi_test --collect-all taichi
```
I haven't tested for Taichi, but it works for other libraries.

**Comment by neozhaoliang** [comment]
Reopen this issue as it's not fixed yet

**Comment by neozhaoliang** [comment]
@compik710 I think this is not a problem with Taichi. The error occurs because Pyinstaller only compiles the .pyc files, but Taichi uses the `inspect` module to parse the original source file. I guess the right solution is make Pyinstaller can find your source code?

**Comment by fangde** [comment]
I manged to get a work around demo working.
It seems the reason is the taichi using inspect to read the source code,
while the pyinstaller pack everyting in to .pyc file,
making the inspect unable to read the source code.
to debug, a simple example to inspect.getsource, whenever inspect.getsource works, the taichi can compile and run the kernel.


for ref
https://stackoverflow.com/questions/61379330/problem-with-inspect-using-pyinstaller-can-get-source-of-class-but-not-function


To make it work,  I have to put all the kernel code into a seprate file and use import the code dynamically. use importlib rather than import,  and also add the path to system enable the exe find the local .py file


```

## test_inspect.py 
import inspect


import sys
import os





sys.path.append(os.getcwd())

import importlib 

# load the mode dyanically from sys.path
code=importlib.import_module('cc')

import taichi as ti 
ti.init(arch=ti.gpu)

if __name__=="__main__":
   

   #check the system include the cwd
    print(sys.path)
   
   #try to get the source for code.hello
    ff=inspect.getsourcefile(code.hello)
    print('modelfil',ff)
    src=inspect.getsource(code.hello)
    print(src)

    #test the kernel
    code.hello()
    
```

the taichi kernel source is put into a seprate file

```
#cc.py
import taichi as ti 
#ti.init(arch=ti.gpu)

@ti.kernel
def hello():
    for i in range(100):
        print(i,"hello")
```

using pyisntaller, success fully generate the exe
> pyinstaller -F -c test_inpsect.py
126 INFO: PyInstaller: 5.6.2
126 INFO: Python: 3.9.13 (conda)
137 INFO: Platform: macOS-12.4-arm64-i386-64bit
138 INFO: wrote /Users/fliu/pack-taichi/test_inpsect.spec
140 INFO: UPX is not available.
141 INFO: Extending PYTHONPATH with paths
['/Users/fliu/pack-taichi']
311 INFO: checking Analysis
329 INFO: checking PYZ
344 INFO: EXE target arch: arm64
344 INFO: Code signing identity: None
345 INFO: checking PKG
346 INFO: Bootloader /Users/fliu/anaconda3/envs/pack/lib/python3.9/site-packages/PyInstaller/bootloader/Darwin-64bit/run
346 INFO: checking EXE



and the test give output
>./dist/test_inpsect              
[Taichi] version 1.2.1, llvm 10.0.0, commit 12ab828a, osx, python 3.9.13
[Taichi] Starting on arch=metal
['/var/folders/vp/7f4bg1px4l39hx4fbtt3__3c0000gp/T/_MEIsuRHow/base_library.zip', '/var/folders/vp/7f4bg1px4l39hx4fbtt3__3c0000gp/T/_MEIsuRHow/lib-dynload', '/var/folders/vp/7f4bg1px4l39hx4fbtt3__3c0000gp/T/_MEIsuRHow', '/Users/fliu/pack-taichi']
modelfil /var/folders/vp/7f4bg1px4l39hx4fbtt3__3c0000gp/T/_MEIsuRHow/taichi/lang/kernel_impl.pyc
@ti.kernel
def hello():
    for i in range(100):
        print(i,"hello")

> 32 hello
33 hello
34 hello
35 hello
36 hello
37 hello
38 hello
39 hello
40 hello
41 hello
42 hello
43 hello
44 hello
45 hello
46 hello
47 hello
48 hello
49 hello
50 hello
51 hello
52 hello
53 hello
54 hello
55 hello
56 hello
57 hello
58 hello
59 hello
60 hello
61 hello
62 hello
63 hello
0 hello
1 hello
2 hello
3 hello
4 hello
5 hello
6 hello
7 hello
8 hello
9 hello
10 hello
11 hello
12 hello
13 hello
14 hello
15 hello
16 hello
17 hello
18 hello
19 hello
20 hello
21 hello
22 hello
23 hello
24 hello
25 hello
26 hello
27 hello
28 hello
29 hello
30 hello
31 hello
96 hello
97 hello
98 hello
99 hello
64 hello
65 hello
66 hello
67 hello
68 hello
69 hello
70 hello
71 hello
72 hello
73 hello
74 hello
75 hello
76 hello
77 hello
78 hello
79 hello
80 hello
81 hello
82 hello
83 hello
84 hello
85 hello
86 hello
87 hello
88 hello
89 hello
90 hello
91 hello
92 hello
93 hello
94 hello
95 hello

**Comment by fangde** [comment]
[归档.zip](https://github.com/taichi-dev/taichi/files/9966900/default.zip)

**Comment by fangde** [comment]
i've attached the test code and build script.
only on mac and with a kernel func. not sure all the features are suported

**Comment by neozhaoliang** [comment]
Thank you very much for the effort and this sharing!

**Comment by shouldsee** [comment]
is pyinstaller the best way to compile taichi python projects for the moment? Or is the cpp aot workflow the preferred option?
<https://github.com/taichi-dev/taichi-aot-demo/blob/master/tutorial.md>
