### ISSUE TITLE
Strange behavior in ggui

### ISSUE THREAD

**Issue by BillXu2000** [taichi-dev/taichi#5131]
**Describe the bug**
Please run the code below.
If line 27 (`pos.to_numpy()`) is removed, the position of balls are not same as the values in set_x function.

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.cpu)

pos = ti.Vector.field(3, dtype=ti.f32, shape=100)

@ti.kernel
def set_x():
    for i in range(pos.shape[0]):
        pos[i] = [i for j in ti.static(range(3))]
set_x()

window = ti.ui.Window("simp fluid", (768, 768))
canvas = window.get_canvas()
scene = ti.ui.Scene()
camera = ti.ui.make_camera()
camera.position(2, 2, 2)
camera.lookat(0, 0, 0)
camera.up(0, 1, 0)
camera.fov(45)

unused = ti.field(ti.f32)
block = ti.root.pointer(ti.ij, (2,1))
pixel = block.dense(ti.ij, (1,1))
pixel.place(unused)

pos.to_numpy()

while window.running:
    camera.track_user_inputs(window, movement_speed=0.03, hold_key=ti.ui.RMB)
    scene.set_camera(camera)
    scene.ambient_light((0.5, 0.5, 0.5))
    scene.point_light(pos=(0.5, 1.5, 0.5), color=(1, 1, 1))
    scene.point_light(pos=(0.5, 1.5, 1.5), color=(1, 1, 1))
    scene.particles(pos, color = (218.0/255.0, 44.0/255.0, 67.0/255.0), radius = 0.1)
    canvas.scene(scene)
    window.show()
    
```

**Log/Screenshots**
Balls are expected to be put in a line.
If line 27 (`pos.to_numpy()`) is removed, there is only one ball (or perhaps multiple balls share the same position) positioned at (0, 0, 0).

**Comment by Morcki** [comment]
The key point about this problem is `unused = ti.field(ti.f32)`.

In this python script, `pos` which you define it as a ti.Vector.field, is on ti.root.snode_tree_0. After you run `set_x` kernel, the whole snode tree is then materialized. 

So then you define `unused = ti.field(ti.f32)` which is now placed  on ti.root.snode_tree_1. But this time, you didn't write any functions to fill value or use it. So snode_tree_1 is not materialized.

When you run `scene.particles`, there is a vbo(vertex buffer object) field which is defined in GGUI part, so the vbo field is stored under snode_tree_1. At present, snode_tree_1 has 2 branches, `unused` on branch_0, `vbo_field` on branch_1. So the really vbo data contains your `unused` data.

To fix this, you need to run `ti.lang.impl.get_runtime().materialize()` which is within ti.sync() and to_numpy() function, which place your `unused` on snode_tree_1, and our vbo field on snode_tree_2.

The process is as below:
```python
# Original Code Process
# read vbo data on snode_tree_1
#               snode_tree_1
# ==============|================|
#     branch_0  |     branch_1   |
#     unused    |  our vbo_field |
# --------------------------------
# vertex| normal|tex_coord| color|

# After you add one line in your python script
# the process change to this situation
...
unused = ti.field(ti.f32)
block = ti.root.pointer(ti.ij, (2,1))
pixel = block.dense(ti.ij, (1,1))
pixel.place(unused)

# run this method or run pos.to_numpy() / ti.sync()
ti.lang.impl.get_runtime().materialize()

while window.running:
     ...

# read vbo data on snode_tree_2
#   snode_tree_1
# ===============|
#      branch_0  |
#       unused   |
# ------------------------------------------
#          snode_tree_2
# ===============================|
#             branch_0           |
#         our vbo_field          |
# --------------------------------
# vertex| normal|tex_coord| color|
#
# This time we read data from snode_tree_2 to get vertex pos, 
# normal and so on instead of reading from snode_tree_1.
```

**Comment by bobcao3** [comment]
Should be fixed, GGUI no longer uses interops and no longer relies on the memory layout of SNode trees
