### ISSUE TITLE
Inconsistent execution speed of to_numpy() operation

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#5156]
Hi,

I am new to taichi and is a bit confused about the execution speed of the to_numpy() operation. What I am doing in the following code snippet is assigning random value to a taichi field and convert it to numpy. What's weird is if more assignment happens before the to_numpy conversion, the slower the conversion is.

To reproduce this behavior: 
```
import taichi as ti
import numpy as np
ti.init(arch=ti.gpu)

field = ti.Vector.field(3, dtype=ti.f32, shape=(500, 500))

@ti.kernel
def render():
    for i, j in field:
        field[i, j] = ti.Vector([0.30, 1.4, 1.0]) * ti.random()


from time import time
while True:
    T = 1
    for i in range(T):
        render()
    t = time()
    field_np = field.to_numpy()
    print(time()-t)
```

When T = 1, the printed time is 0.02s. With T = 20, the time bumps up to 0.45.
I am not expecting this because the field is a constant-size variable. 

Could you please provide any insight and potentially any fix regarding this?
Thanks!

**Comment by bobcao3** [comment]
The backend scheduling may not and actually do not execute all the `render` call immediately and it does not wait until previous calls to finish unless there is an dependency. This is normal behavior caused by more advanced scheduling. If you put a `ti.sync()` after the loop and forces the backend to wait until all work has finished, you will see a more consistent time (however as an result lose a bit of performance)

**Comment by bobcao3** [comment]
If you have further questions feel free to re-open the issue
