### ISSUE TITLE
Unexpected results when iteration range exceeds INT_MAX

### ISSUE THREAD

**Issue by lucifer1004** [taichi-dev/taichi#5217]
**Describe the bug**
Taichi yields unexpected results when the iteration range is very large (exceeding INT_MAX).

**To Reproduce**

```py
import taichi as ti

ti.init(arch=ti.gpu)

n = 10
m = 10000000000
a = ti.field(dtype=ti.i64, shape=(n,))


@ti.kernel
def calc():
    for i in range(ti.i64(m)):
        a[i % n] += 1

calc()
print(a)
```

**Log/Screenshots**
Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening. For example:

```
$ python my_sample_code.py
[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, linux, python 3.9.12
[Taichi] Starting on arch=cuda
[141006541 141006541 141006541 141006541 141006541 141006541 141006541
 141006541 141006540 141006540]
```

For `m = 3000000000`, the result is:

```
[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, linux, python 3.9.12
[Taichi] Starting on arch=cuda
[0 0 0 0 0 0 0 0 0 0]
```

For `m = 2000000000`, the result is correct:

```
[Taichi] version 1.0.3, llvm 10.0.0, commit fae94a21, linux, python 3.9.12
[Taichi] Starting on arch=cuda
[200000000 200000000 200000000 200000000 200000000 200000000 200000000
 200000000 200000000 200000000]
```

**Additional comments**

**Comment by lucifer1004** [comment]
@turbo0628 My actual use case does not require such a large range. I ran into this issue when I did some benchmarking.

**Comment by jim19930609** [comment]
Two issues I can think of:

1. Range_For implicitly cast "begin" and "end" to ti.i32, so it overflows once reached MAX_INT32 (2,147,483,647) instead of MAX_INT64.

![2022-06-24 10-43-51 的屏幕截图](https://user-images.githubusercontent.com/22334008/175451754-2c5474e6-bc90-4a08-b7f4-3996631c1a15.png)

We should add an overflow check for this specific cast since it's implicit.

2. Taichi to provide some runtime overflow check under Debug mode. This is more like a "nice to have".
