### ISSUE TITLE
Improve format server UI

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#621]
**Concisely describe the proposed feature**

Currently, the format server has a rather minimal UI. It's very easy for people to misclick:

![Screenshot from 2020-03-18 23-56-41](https://user-images.githubusercontent.com/6553256/77030152-2b315e80-6974-11ea-97ee-ac9bc48f8281.png)

**Describe the solution you'd like (if any)**

Two ways: 
 - (A) Interface the web API with GitHub action so that users can format their PR by simply clicking a button
 - <strike> (B) Improve the web UI to avoid misclicking (say pop up a confirmation msgbox) </strike>

The first way is more systematic yet also more challenging to implement. The second way can be a temporary solution. 

**Additional comments**
You can start the server locally by `python3 misc/format_server.py`. Thanks!

**Comment by archibate** [comment]
Cool! To disable misclick in plan B, you want to:
1. Seek history to find which PR does user come from.
2. Specify GET argument in PR template `[Click to format]`.

**Comment by yuanming-hu** [comment]
> Cool! To disable misclick in plan B, you want to:
> 
> 1. Seek history to find which PR does user come from.
> 2. Specify GET argument in PR template `[Click to format]`.

Yeah, this sounds reasonable. However, I'm not sure if it is possible to get the users's history and github account.

(I'm not a web expert...)

**Comment by archibate** [comment]
I'm thinking about [Click to format] instead of [Click here for the format server], do you know if `api.github.com` provides user infomation access? Basically user name, user permissions to our repo.

**Comment by yuanming-hu** [comment]
> 2\. Specify GET argument in PR template `[Click to format]`.

Yeah, I tried this one but failed to find something like `${GITHUB_PR_ID}`...


> I'm thinking about [Click to format] instead of [Click here for the format server], only PR author and reviewers can click it, do you know if `api.github.com` provides user information access? Basically user name, user permissions to our repo.

I have no idea about that, sorry...

**Comment by archibate** [comment]
Found https://developer.github.com/v3/users/#example-1

**Comment by archibate** [comment]
According to https://www.w3school.com.cn/jsref/dom_obj_history.asp:

> History 对象最初设计来表示窗口的浏览历史。但出于隐私方面的原因，History 对象不再允许脚本访问已经访问过的实际 URL。唯一保持使用的功能只有 back()、forward() 和 go() 方法。

Plan 1 dead.

**Comment by archibate** [comment]
test content, no reply:
<a href="https://archibate.github.io/grapher">test</a>

**Comment by rexwangcc** [comment]
Sorry I come to this party late. I came across this issue from #620 and #677 (`Set up Cpplint
 Set up pylint`).

With a simple test it seems both (A) and (B) are feasible, and I already see some progress on (B). But I also want to bring up a potential solution (C) which is a one step further variant of (B): hand off the actual formatting and committing job to Github Actions, instead of just sending a request to the format server.

Comparison:
(A) (B) both put some traffic/maintaincen presure on the centralized format server but give developers more flexibility, while the logs are not easily available to the developers so extra back and forth might need to happen if something goes wrong.

(C) will lift up the stress on the server and natually distribute the work across Github Actions runners, which, in the free tier, provides up to 6 hour free time. Problem is that the runner VM (docker container)s are one-off, so without proper cache set up, there will be a lot of overhead each time a format job gets executed by the runners, this depends on how easily can a `ti.format` be setup in a fresh VM from scratch. 

I'm not leaning towards either but the way the current format server's set up really triggered my worry (I almost mis-clicked others' PR while looking through it...), and I believe it's not just a UX design issue but can become real problems from the security and turnaround perspectives as it gets more attention...

**Comment by rexwangcc** [comment]
By the way, if I could get some help from mantainers who have access to the diligent @taichi-gardener to create an Github OAuth application, and discuss about how/where to safely store the OAuth client ID/secret, I could make a PR to implement (A) soon. (If it goes well hopefully it could also address issue #620 by setting up OAuth for the server and authenticate every request (if we still want to keep the server up and running in the future).)

**Comment by yuanming-hu** [comment]
> Sorry I come to this party late.

Welcome!

A few things that need checking out:

 - Related (new) issue:  https://github.com/taichi-dev/taichi/issues/956
 - Related (new) PR by @archibate: https://github.com/taichi-dev/taichi/pull/957

Actually, I believe many of the current developers are leaning towards (C) now.

**Comment by rexwangcc** [comment]
Thanks for the prompt 🚀 reply! I will take a look at the issues/PRs above.

It seems #957 is going down the path A, but once the first draft is setup it will be pretty easy to iterate on it!

>The @taichi-gardener account is managed by me - if you need access to this account, please feel free to let me know :-)

Thanks, I think we only need to bother the gardener if we want to go with path B and add OAuth and Authentication on the server. Most of the development work before the final step could be done with my testing accounts.

**Comment by yuanming-hu** [comment]
> It seems #957 is going down the path A, but once the first draft is setup it will be pretty easy to iterate on it!

Right, I guess as time goes by we will end up with something similar to https://github.com/halide/Halide/blob/master/.github/workflows/presubmit.yml

**Comment by rexwangcc** [comment]
Yup! (only diffrence might be we are talking about both `lint` and `format` here but that one looks more like just lint checks, which is relatively faster)

**Comment by rexwangcc** [comment]
It turns out to be really easy to test path B, like: https://github.com/login/oauth/authorize?client_id=9a3d7e41ce82a8dc1f6b&redirect_uri=http://kun.csail.mit.edu:31415/

Note the `code=xxx` i the redirected server URI, which then can be used by the server to filter out PRs that not belong to the user.

**Comment by yuanming-hu** [comment]
Looks really cool! Thanks for setting up GitHub OAuth. I believe it will be useful for future applications.

I personally think, however, it is better to directly proceed to (C) and abandon the format server (which I wrote a couple of months ago and I believe it has contributed enough...) For mechanical jobs like enforcing formats, we should probably trust machines (GitHub Actions) other than humans.

**Comment by rexwangcc** [comment]
Yeah, I strongly agree if that's the concensus here! Having de-centralized CI runners will bring a lot of convenience for external contributors.
