### ISSUE TITLE
[Bug] Numerical error with Taichi v1.2.0

### ISSUE THREAD

**Issue by turbo0628** [taichi-dev/taichi#6441]
Thanks to @lucifer1004 who encountered this bug in his development.

This bug is backend neural: cpu / cuda / vulkan all behave consistently.

[Minimal reproduction](https://github.com/turbo0628/TaichiCloud/blob/main/TaichiCloud/reprod.py)

Briefings:

The `init` part is good, but the main function `adj_cellwise_hlpr ` gets unexpected value in the field `self.f_r` if you comment out the `print` statement at [this line](https://github.com/turbo0628/TaichiCloud/blob/main/TaichiCloud/reprod.py#L109). 

The v1.1.3 has no numerical problem. We should check which newly added pass caused the error.

**Comment by lin-hitonami** [comment]
It's my fault. `cache_loop_invariant_global_vars` pass does not set the init value to the cached variable if the first instruction in the block accessing the variable is store (in this case it may not be executed because it is after a conditional break). The easiest fix is setting the init value all the time.
