### ISSUE TITLE
Performance implications of dynamic indexing

### ISSUE THREAD

**Issue by AmesingFlank** [taichi-dev/taichi#7185]
I have a rather large taichi program, which I wrote before `dynamic_indexing` is enabled by default, it contained a lot of loops unrolled using `for i in ti.static(range(..))`.  Now that  `dynamic_indexing` is the default, I decided to try rewriting my program to always use dynamic indices. I noticed that after dynamic indices are used, the performance of the program dropped by around 15%. I mostly use the CUDA backend.

So my questions are:
* Is the performance drop expected?
* Are there any general guidelines of when should loop-unrolling should be preferred over dynamic indexing in terms of performance? What are the rules of thumb?

@strongoier 
Thanks!

**Comment by strongoier** [comment]
Thanks for your feedback on trying the feature!

> Is the performance drop expected?

Yes. The reason is that for a local matrix, the internal representation goes from multiple scalars to an array.

> Are there any general guidelines of when should loop-unrolling should be preferred over dynamic indexing in terms of performance? What are the rules of thumb?

We don't expect users to rewrite all their previous programs at this moment. For those matrices with only constant indices required, using loop-unrolling can optimize the array representation to scalars so as to achieve best performance. Of course, automatic loop-unrolling in certain cases can be an optimization opportunity in Taichi in the future.

For now, just as the release note says,

> Before v1.4.0, when you wanted to access a vector/matrix with a runtime variable instead of a compile-time constant, you had to set ti.init(dynamic_index=True). However, that option only works for LLVM-based backends (CPU & CUDA) and may slow down runtime performance because all matrices are affected. Starting from v1.4.0, that option is no longer needed. You can use variable indices whenever necessary on all backends without affecting the performance of those matrices with only constant indices.

The removal of the option is most beneficial for cases where the dynamic index feature is really needed (i.e., loop-unrolling cannot solve their problem).

**Comment by AmesingFlank** [comment]
I see. This makes sense. Many thanks for your explanation!
