### ISSUE TITLE
How to release gpu memory when deleting field

### ISSUE THREAD

**Issue by zhouxian** [taichi-dev/taichi#8214]
The following snippet throws out of cuda memory error:
```python
import taichi as ti
ti.init(ti.gpu, device_memory_GB=1)
a = ti.field(int, (20000, 10000))
a.fill(1)
del a
a = ti.field(int, (20000, 10000))
a.fill(1)
```
I understand we can use FieldsBuilder to manually manage memory, but in the doc it says "Generally, Taichi manages memory allocation and destruction without disturbing the users." I wonder: how does memory release work? when will memory associated with deleted field be release?

**Comment by lin-hitonami** [comment]
Taichi does not release the memory of the field if you delete it because we manage the memory of the fields using something called SNode tree. A SNode tree can contain multiple fields, and the memory of these fields are managed together, which means that sometimes we cannot release the memory of a field without releasing the memory of other fields in the SNode tree. 

By using FieldsBuilder, you create a SNode tree. When you destroy a SNode tree, the memory of all fields it contains can be freed at once.
