### ISSUE TITLE
What is RMB?

### ISSUE THREAD

**Issue by kurt-rhee** [taichi-dev/taichi#8252]
https://docs.taichi-lang.org/api/taichi/ui/#taichi.ui.RMB

In the documentation above, I am not sure what RMB means.

**Comment by kurt-rhee** [comment]
Does this mean "right mouse button?"

**Comment by JiangYuanzhang** [comment]
CNY

**Comment by JiangYuanzhang** [comment]
> https://docs.taichi-lang.org/api/taichi/ui/#taichi.ui.RMB
> 
> In the documentation above, I am not sure what RMB means.

CNY

**Comment by houkensjtu** [comment]
> Does this mean "right mouse button?"

Exactly. You can try out the example here : https://docs.taichi-lang.org/docs/ggui#3d-geometries

In the ui's main loop, there is a line specifying the behavior of the camera:
```python
while window.running:
    camera.track_user_inputs(window, movement_speed=0.03, hold_key=ti.ui.RMB)
```
This means that you can hold the "right mouse button" to rotate the camera. You can change the `hold_key` to `ti.ui.LMB` so that you can hold the "left mouse button" to rotate.

And unfortunately, RMB != CNY in Taichi ;)
