### ISSUE TITLE
[misc] do we have clang-9 support?

### ISSUE THREAD

**Issue by archibate** [taichi-dev/taichi#878]
**Concisely describe the proposed feature**
It's hard to make user to install a non-latest version of `clang`. So I would like to add `clang-9` support so no more dep issues on clang will occur.
Also note that we detect `clang` in `$PATH` instead of a absolute path... it's bad for those people who have many clang&llvm instances for statifying their other repos..

**Describe the solution you'd like (if any)**
Sorry I'm not an expert on compilers so I've no idea..

**Additional comments**
May also consider the possibility of `gcc`, which is more commonly used by users?

**Comment by yuanming-hu** [comment]
Thanks for proposing. I've never tried clang-9, but I assume the compatibility should be not too bad.

Same for gcc, but I guess making gcc-7 work would be harder... Note that for developers clang is always needed since they need to compile the runtime llvm bitcode.


> Also note that we detect `clang` in `$PATH` instead of a absolute path... it's bad for those people who have many clang&llvm instances for statifying their other repos..

Right, if we stick with clang, maybe we should pass `CMAKE_CXX_COMPILER` as a macro to the source code, so that the same clang will be used for both bitcode and `taichi_core` compilation: https://github.com/taichi-dev/taichi/blob/cecb7ca43a52e4b5826d86e991c10dc6117aac2c/CMakeLists.txt#L74

**Comment by archibate** [comment]
> Thanks for proposing. I've never tried clang-9, but I assume the compatibility should be not too bad.

So the major problem is, when using `clang-9`, the generated LLVM IR causes some problem like `llvm-as: error: %4 shouldn't be followed by %5`.

> Right, if we stick with clang, maybe we should pass `CMAKE_CXX_COMPILER` as a macro to the source code, so that the same clang will be used for both bitcode and `taichi_core` compilation:

+1, will try to do this one later.

**Comment by bobcao3** [comment]
Should be supported as of now.
