### ISSUE TITLE
[misc] Always enforce code format using GitHub Actions/Workflows

### ISSUE THREAD

**Issue by yuanming-hu** [taichi-dev/taichi#956]
**Concisely describe the proposed feature**
As proposed by @archibate (https://github.com/taichi-dev/taichi/pull/954#issuecomment-627083524) it's time to consider enforce code formats automatically. Relying on humans to always trigger `ti format` or use the format server sounds a little unrealistic and complicates our workflow.

**Describe the solution you'd like (if any)**
Halide has a github workflow which we can learn from: https://github.com/halide/Halide/blob/master/.github/workflows/presubmit.yml

**Comment by archibate** [comment]
https://github.com/taichi-dev/taichi/blob/e0ef399b2c2f053918e1013fea9850022c96bced/appveyor.yml#L48
We can reuse the previous attempt in appveyor `[format]`: trigger format server by `curl` in action.yml.

**Comment by rexwangcc** [comment]
Regarding performence benchmark, it's probably a bit tricky to benchmark the real formating part since it will require someone to setup a huge number of bogus PRs. (we could do that in a separate made up repo tho). But with `locust` stress testing a local format server on my box in a few minutes, I can already see failures when there are ~108 concurrent users (108 request per seconds) checking the server (GET /, not even click format, which only asks the user to request PR lists from Github API), and then the server breaks:

![locust](https://user-images.githubusercontent.com/14366016/82006110-0e906a80-9635-11ea-86a0-e21adbe49274.png)

Well, given:
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

I think my IP is banned by Github API now for unauthenticated requests, so it's expected.

**Comment by archibate** [comment]
How about just make `format_server.py` login GitHub as @taichi-gardener?
